### ISSUE TITLE
Having issues patching the rando seed to the game file for Dread

### ISSUE THREAD

**Issue by TigerzRevenge** [randovania/open-dread-rando#179]
When I try to patch for Ryujinx, I get an unhandled exception error box with the following log:

Traceback (most recent call last):
  File "randovania\gui\lib\game_exporter.py", line 44, in export_game
  File "randovania\gui\lib\background_task_mixin.py", line 70, in run_in_background_async
  File "randovania\gui\lib\background_task_mixin.py", line 62, in work
  File "randovania\gui\lib\game_exporter.py", line 34, in work
  File "randovania\exporter\game_exporter.py", line 42, in export_game
  File "randovania\games\dread\exporter\game_exporter.py", line 82, in _do_export_game
  File "open_dread_rando\patch_util.py", line 46, in patch_with_status_update
  File "open_dread_rando\dread_patcher.py", line 132, in patch_extracted
  File "open_dread_rando\patcher_editor.py", line 24, in __init__
  File "mercury_engine_data_structures\file_tree_editor.py", line 73, in __init__
  File "mercury_engine_data_structures\file_tree_editor.py", line 89, in _update_headers
  File "pathlib.py", line 1126, in read_bytes
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Switch Files\\Metroid Dread [010093801237C000][v0](Dumped).xci\\system\\files.toc'

Am I missing an important file somewhere?

**Comment by duncathan** [comment]
you need to extract the romfs before patching. randovania can't extract it from the xci - use ryujinx to do it
