### ISSUE TITLE
Artaria crash in EMMI zone

### ISSUE THREAD

**Issue by steven11sjf** [randovania/open-dread-rando#378]
Might look into this later if I feel like pulling up a 210 exefs in ghidra. 

steps taken:
- entered artaria through thermal device
- double clipped with freesink from magma flow vista -> east lava missile room -> path to thermal device
- activate thermal device
- exit through invisible corp room (already open), then go through nav station and into zone via bottom door (`DoorEmmy006`)
- emmi spawned at `LM_EmmyEntrancePoint_000`
- run to door, holding spark while it opens and *walking* through (while timer ran out)
  - based on minimap, emmi walked left through `DoorPowerPower_001` and went up towards the ledge above
- game crashed during transition

```01:28:06.230 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Metroid Dread, PID: 127
   0x00000000085044b0	main:0x04b0	
   0x00000000086b83a4	main:0x1b43a4	
   0x0000000009078e18	main:0xb74e18	
   0x0000000009078c04	main:0xb74c04	
   0x000000000956cac0	main:0x1068ac0	
   0x000000000956b924	main:0x1067924	
   0x000000000969dfc4	main:0x1199fc4	
   0x0000000008caa834	main:0x7a6834	
   0x0000000008737858	main:0x233858	
   0x000000000927fe64	main:0xd7be64	
   0x00000000096a7a20	main:0x11a3a20	
   0x00000000094b0754	main:0xfac754	
   0x00000000094b0234	main:0xfac234	
   0x00000000093ea338	main:0xee6338	
   0x00000000093e8a0c	main:0xee4a0c	
   0x0000000008504f6c	main:0x0f6c	
   0x000000000863682c	main:0x13282c	
   0x0000000008505920	main:0x1920	nnMain:0x0030
   0x000000007bac64c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000085000d4	rtld:0x00d4	


01:28:06.232 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000002126011a48
	X[01]:	0x0000000000009537
	X[02]:	0x0000000000000008
	X[03]:	0x0000000000000025
	X[04]:	0x0000000000000001
	X[05]:	0x0000000000000b50
	X[06]:	0x000000000000000a
	X[07]:	0x7f7f7f7f7f7f7f7f
	X[08]:	0x0000002125fc7090
	X[09]:	0x0000000000008602
	X[10]:	0x0000000000008602
	X[11]:	0x00000000000000cb
	X[12]:	0x0000000009b4ad68
	X[13]:	0x000000107c6fe318 (SP:-0x0118)
	X[14]:	0x07d9ba1385133664
	X[15]:	0x00000000000000e5
	X[16]:	0x000000000a1bd050
	X[17]:	0x000000007bd75860 (sdk:0x55f860)	=> strlen
	X[18]:	0x0000000000080000
	X[19]:	0x0000000000000013
	X[20]:	0xbd5d677d5c04a4c7
	X[21]:	0x000000107c6fe308 (SP:-0x0108)
	X[22]:	0x0000000000000001
	X[23]:	0x0000000000000000
	X[24]:	0x000000000a24b110
	X[25]:	0x000000107c6fe418 (SP:-0x0218)
	X[26]:	0x000000213dc1a2c0
	X[27]:	0x00000021297e1000
	X[28]:	0x000000211b315500
	FP:	0x000000107c6fe250 (SP:-0x0050)
	LR:	0x00000000085842c8 (main:0x802c8)	=> 
	SP:	0x000000107c6fe200 (SP)
	PC:	0x0000000008584824 (main:0x80824)	=> 


01:28:06.267 |N| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()
```

**Comment by Miepee** [comment]
related to #362 ?

**Comment by steven11sjf** [comment]
Possibly? This one was inside the zone rather than at the entrance.
