### ISSUE TITLE
Collecting Progressive Suit causes a crash on emulator

### ISSUE THREAD

**Issue by ScorelessPine** [randovania/open-dread-rando#50]
(Untested on console)
~~As in the title, collecting a progressive suit in a heated room seems to cause a crash. It may be possible that Gravity Suit in Cold Rooms may cause the same issue, but it is unknown. Attached is a zipped rdvgame where the bug can be found (generated on dev213) and an image of the location where this progressive suit was found.
This isn't an immediate issue considering heat/cold runs are not recommended to use, however if/when damage runs are used in the future, this could pose a problem.~~
EDIT: I may have spoken too soon, picking up another progressive suit elsewhere also caused a crash. It may not be the cause in the title, however crashes are still not good.

![image](https://user-images.githubusercontent.com/28274052/154694343-04da029f-a351-4c90-b404-4801a7cfaf33.png)
[Dread Randomizer - Spreader Shrine Hall.zip](https://github.com/randovania/open-dread-rando/files/8097664/Dread.Randomizer.-.Spreader.Shrine.Hall.zip)

**Comment by Unknownforce351** [comment]
```
00:27:17.594 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: ability
 Report: {
    "SaveDataID": "d6eaa71c-6908-42a4-a672-e818c03f070c",
    "PlayTime": 1709,
    "CumulativePlayTime": 1796,
    "GameProgressID": 3,
    "Mode": 0,
    "SessionID": "b813e675-eb25-4c8a-a3e0-d052df1afad0",
    "ObtainedAbilityID": 0
}

00:27:17.761 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: GameApp, PID: 92
   0x00000000081c8588	main:0x1c4588	
   0x00000000081d32b0	main:0x1cf2b0	
   0x00000000081df9a8	main:0x1db9a8	
   0x00000000081de7e8	main:0x1da7e8	
   0x00000000081e2ac4	main:0x1deac4	
   0x00000000082153e8	main:0x2113e8	
   0x00000000081f351c	main:0x1ef51c	
   0x0000000008200588	main:0x1fc588	
   0x0000000008005328	main:0x1328	
   0x000000000813663c	main:0x13263c	
   0x0000000008005920	main:0x1920	nnMain:0x0030
   0x000000007b3294c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:27:17.765 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x00000065fb1f5a70
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x000000007b4eccb0 (sdk:0x473cb0)	=> 
	X[06]:	0x0000000000000001
	X[07]:	0x0000004a5e308910 (SP:-0xffffffffffffff10)
	X[08]:	0x0000000000000000
	X[09]:	0x0000000009d04120
	X[10]:	0x00000065fe370df0
	X[11]:	0x00000000000010c0
	X[12]:	0x00000066013c75a0
	X[13]:	0x00000000000010c0
	X[14]:	0x2a1ba9f3decc1b03
	X[15]:	0x0000000000000000
	X[16]:	0x0000000009c76f00
	X[17]:	0x000000007b5b3d78 (sdk:0x53ad78)	=> memcpy
	X[18]:	0x000000008d00ffbc
	X[19]:	0x00000065f7ffa5a0
	X[20]:	0x0000006601395330
	X[21]:	0x00000065fb1f5a70
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000001
	X[25]:	0x00000065fb1750c8
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000360
	X[28]:	0x0000000076552fc8
	FP:	0x0000004a5e308a60 (SP:-0x0060)
	LR:	0x00000000081d424c (main:0x1d024c)	=> 
	SP:	0x0000004a5e308a00 (SP)
	PC:	0x0000000000000000


00:27:17.765 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:27:17.825 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
```

**Comment by duncathan** [comment]
updating the suit model while any VFX is active causes the crash
